packages:
    - 'packages/*'
    - 'apps/*'

catalog:
    '@primeuix/themes': ^1.2.1
    'tailwindcss-primeui': ^0.6.1
    '@primevue/nuxt-module': ^4.3.6
    'primevue': ^4.3.6
    'primeicons': ^7.0.0
    '@primevue/forms': ^4.3.6

catalogs:
    app:
        'nuxt': ^3.15.4
        'vite': 6.0.11
        'sass': 1.45.0
        'sass-loader': 8.0.2
        '@docsearch/js': ^3
        'chart.js': 3.3.2
        'quill': 2.0.0
